### ISSUE TITLE
Are you still interested in working on this?

### ISSUE THREAD

**Issue by lmaccherone** [lcrespom/purecheck#1]
I'm developing a product where I'm thinking of defining a domain specific language for users of my system to specify validation for their entities, but I'd prefer to just allow them to write their own pure JavaScript functions. I have the ability to isolate the execution of these functions, but there is really no need for the user to provide impure functions so I want to implement this check as another layer of security. The situation is a bit easier in my case because everything is JSON parsed before being passed into the function so there is no risk of a custom toNumber() call. Would you be open to a bounty to implement the whitelist function call feature and maybe a few other things?

**Comment by lcrespom** [comment]
Hello Larry,

Thank you for your interest. Could you please explain what you you mean by "a bounty"? Is it some GitHub thing?

Luis.

**Comment by lmaccherone** [comment]
https://en.wikipedia.org/wiki/Open-source_bounty

**Comment by lcrespom** [comment]
That is very interesting :-).

I would be doing this in my free time, so I cannot commit any due date, but I will have some time during Christmas.

Could you describe the requirements, also provide some examples?

**Comment by lmaccherone** [comment]
Off the top of my head:

1. The only data used on the right side of an assignment comes from the function's parameters, literals, or locally scoped variables previously derived from the function's parameters. I refer to this as a taint check below. Getting anything from `this` or some other global scope is not allowed.
2. Similarly, only data derived from the parameters, locally scoped variables, or literals are allowed to be passed back in the function's `return` statement.
3. Known pure standard library function calls are allowed `Math.sqrt()` and probably all `Math.*` as well as string functions and all operators. I assume this will be in a configurable whitelist. 
4. Confirm that the parameters passed into any function are not tainted.
5. The parameters are serialized to a JSON string and then reconstituted upon calling, so I'm not worried about hidden `.toNumber()` calls triggered by JavaScript's aggressive type conversions. In fact, modifying the parameters is perfectly safe for my case, since the JSON string proxy breaks  any connection they had to the outside world.
6. The function must have a `return` statement.
7. If there are locally created functions, the taint analysis must survive calls to them, but I think that's just recursively making sure they are pure also and that none of the parameters passed into them come from a tainted source.

Remember, the use case is to allow the user to specify a function that will run on my own servers so if you can think of any other risks, I'd love to hear about them.

**Comment by lmaccherone** [comment]
Ohh, here's 1.5 Everything on the left side of an assignment, must be locally scoped. Nothing on the left side of an assignment can write to `this` or some other global scope.

**Comment by lcrespom** [comment]
The library will be quite easy to test by providing sample functions, so I can start by defining some simple snippets as test cases, and you can provide your own set.

I agree with most of your points above but I see some problems. For example, you mention there are some pure functions that can be whitelisted, e.g. all string methods (since strings are immutable) and some array methods, e.g. map, filter, reduce, etc. The problem is that in JavaScript there is no way to know the type of a given parameter, so if you see `a.filter()`, you can't be sure whether `a` is an array and therefore `filter` is pure, or else it is some other object which happens to have a non-pure `filter` method.

Also, I think this library should also support ES6, therefore rule 6 should be expanded to "the function must either have a return statement or be a fat arrow expression without curly braces".

I will dedicate some time during the weekend. Could you please provide more details about your bounty proposal?

**Comment by lmaccherone** [comment]
I am willing to live either without things like filter() or take the risk. Remember in my use case, the parameters are all pure JSON so they won't have a filter function unless they are arrays. If a type is created in the function we can check that all its methods are pure, no?

As for the amount of the bounty, what would be a ballpark that would make it worth your while?

**Comment by lcrespom** [comment]
About the list of library pure functions, this white list can be configurable so there should be no risk in enabling them at configuration level.

About the bounty, let me look at it during the weekend, then I will give you a response.

**Comment by lcrespom** [comment]
Hello Larry,

I sent you an e-mail to the address that is displayed in your GitHub profile. Please tell me if you got it.

Luis.

**Comment by bfelbo** [comment]
Hello @lcrespom and @lmaccherone, it was super interesting to stumble across your conversation here.

We're considering a similar use case of allowing users to upload JS functions that will run on our servers. These functions would be pure and checked against a configurable list of allowed syntax.

I'd be very curious to hear if you can share any conclusions on using a library like purecheck for this purpose?

I know this is a quite old conversation and apologize for reviving it, but if you don't mind, I'd really appreciate your thoughts on this 🙏

**Comment by lcrespom** [comment]
Hello Bjarke,

My original idea was to use purecheck from an IDE/editor plugin (mainly
thinking about VSCode) so it can provide instant hints on whether a
function is pure or not.

At its current state, purecheck does not detect 100% of cases and thus
cannot be trusted to automatically validate code that is put in production.
Depending on the purpose and expectations of the validation, it may be OK,
as long as you keep its limitations in mind.

In any case, please let me know if you use it or extend it, it would make
me happy to know people are using it.

Regards,
Luis.

**Comment by bfelbo** [comment]
Thanks for the prompt response, Luis. It looks great and I'd love to explore how we can use it. We'll only need to use it for simple JS so the case coverage might be fine for our use case.

I don't see a license file for the repo. Would you consider licensing it as MIT?

**Comment by lcrespom** [comment]
Hello Bjarke,

Sure, if you need me to add a license file, just let me know.

Regards,
Luis.

**Comment by bfelbo** [comment]
Thanks, would be great if you could do that :)

**Comment by lcrespom** [comment]
Done :-)
